version: "3.7"
services:
  landing:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
