export * from "./x-logo";
export * from "./telegram-icon";
export * from "./youtube-icon";
export * from "./linkedin-icon";
export * from "./right-arrow-icon";
export * from "./eth-icon";
export * from "./btc-icon";
export * from "./signup-icon";
export * from "./gateway-setup-icon";
export * from "./api-paylink-creation-icon";
export * from "./settlement-request-icon";
export * from "./security-measure-icon";
export * from "./global-selling-img";
export * from "./shopping-icon";
export * from "./instant-settlement-icon";
export * from "./credit-card-img";
export * from "./support-icon";
export * from "./crypto-diversity-img";
export * from "./dollar-icon";
export * from "./twenty-four-hour-support-img";
export * from "./iphone-img";
export * from "./darkMode-icon";
export * from "./language-dark-icon";
export * from "./iphone-dark-img";
export * from "./x-dark-logo";
export * from "./telegram-dark-icon";
export * from "./youtube-dark-icon";
export * from "./linkedin-dark-icon";
export * from "./phone-icon";
export * from "./clock-icon";
export * from "./email-icon";
export * from "./location-icon";
export * from "./check-icon.light";
export * from "./back-slash-icon";
export * from "./check-cart-icon";
export * from "./attach-icon"
export * from "./open.collapse"
export * from "./close.collapse"
export * from "./cross-icon-dark"
export * from "./cross-icon-light"
