import type { Metadata } from "next";
import "./globals.css";
import i18nConfig from "../../../i18nConfig";
import { dir } from "i18next";
import localFont from "next/font/local";
import { Providers } from "./provider";
import Header from "@/components/layout/header";
import initTranslations from "../i18n";
import TranslationsProvider from "@/configs/TranslationsProvider";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = localFont({
  src: [
    {
      path: "../../../public/fonts/Poppins-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
});

const yekanBakh = localFont({
  src: [
    {
      path: "../../../public/fonts/YekanBakh-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/YekanBakh-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/YekanBakh-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../../public/fonts/YekanBakh-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-yekanBakh",
});
export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}
const i18nNamespaces = ["translation"];
export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <html
      lang={locale}
      dir={dir(locale)}
      className={`${poppins.variable} ${yekanBakh.variable}`}
      suppressHydrationWarning
    >
      <body>
        <Providers>
          <TranslationsProvider
            namespaces={i18nNamespaces}
            locale={locale}
            resources={resources}
          >
            <Header />
            {children}
            <Footer/>
          </TranslationsProvider>
        </Providers>
      </body>
    </html>
  );
}
