name: Prod Landing Deployment
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 49.13.123.36
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/landing && git reset --hard 
            git pull origin main
            yarn install
            yarn build
            docker compose up -d --build
