name: Prod Landing Deployment
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 168.119.237.221
          username: payment4
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/landing && git reset --hard 
            git pull origin main
            node -v
            yarn install
            yarn build
            docker compose build
            docker compose restart landing
